# Generated by Django 3.2 on 2023-11-01 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='rewiew',
            new_name='review',
        ),
    ]
