# Generated by Django 3.2 on 2023-10-29 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20231028_1316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={},
        ),
        migrations.AddField(
            model_name='comments',
            name='title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='reviews.titles', verbose_name='Произведение'),
            preserve_default=False,
        ),
    ]
