# Generated by Django 3.2 on 2023-11-01 18:12

from django.db import migrations, models
import reviews.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20231101_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[reviews.models.validate_user_name]),
        ),
    ]
