# Generated by Django 3.2 on 2023-11-03 18:34

from django.db import migrations, models
import reviews.models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_users_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[reviews.models.validate_user_name]),
        ),
    ]
